### PR TITLE
Add PHP 8.4 nightly to tests

### PR DESCRIPTION
**Pull request by joanhey**
So we can find problems with time.

PHP 8.4 Timetable
https://wiki.php.net/todo/php84

WIP

### CODE REVIEW

**Comment by joanhey** [comment]
Pest still don't work with PHP 8.4
https://github.com/pestphp/pest/issues/1199

**Comment by joanhey** [comment]
We still have deprecated messages from the Mockery 2 lib.
Mockery 1.6 is fixed for PHP 8.4, but we use v2.0.x that it isn't updated for the last 7 months.
We need to check the differences and change to v1.6.

**Comment by joanhey** [comment]
We have another problem.
Workerman v4.1 also have deprecations:
* explicit nullable type  is only fixable with PHP 7.1 and now only require PHP 7.0
* Constant E_STRICT is deprecated in /home/runner/work/AdapterMan/AdapterMan/vendor/workerman/workerman/Worker.php on line 518

**Comment by walkor** [comment]
> We have another problem. Workerman v4.1 also have deprecations:
> 
> * explicit nullable type  is only fixable with PHP 7.1 and now only require PHP 7.0
> * Constant E_STRICT is deprecated in /home/runner/work/AdapterMan/AdapterMan/vendor/workerman/workerman/Worker.php on line 518

Perhaps we should raise the minimum PHP version for Workerman v4.1 to 8.0.

**Comment by joanhey** [comment]
Never for 4.1, but of course for v4.2
We need to change the composer json, and is ready.

**Pull request merged**
