### PR TITLE
Optimize Worker.php

### PR DESCRIPTION
**Pull request by taozywu**
RT

### CODE REVIEW

**Comment by xpader** [comment]
把 debug_backtrace 存到属性中不是会浪费到更多的内存么，这个也不少啊，而且带来的性能提升对关键业务好像也没有帮助。

**Comment by taozywu** [comment]
@xpader 
the code is defined only in '__construct', after that u can use it. If you worry about the continued use of memory, I think it can be ignored or u  can unset it in time. it is my opinion!

**Comment by walkor** [comment]
Sorry, the pull request is refused because there is no difference after merge the pull request.

**Comment by taozywu** [comment]
@walkor  okay

**Pull request closed without merging**
