### PR TITLE
remove header['server'] for security reasons

### PR DESCRIPTION
**Pull request by amirfaramarzi**
To increase the security of websites, it is better that no one understands what technologies the program uses

### CODE REVIEW

**Comment by detain** [comment]
Personally I would prefer an optional setting to customize the server response string, or set to false to disable it altogether.

**Comment by xpader** [comment]
Add an option is a good way to do that.

**Comment by sangyuxiaowu** [comment]
Security should not just do superficial work, modify the return of the server logo, whether it is confusing or removing, the existing loopholes still exist.

The logo of the server has other uses, and it is also a symbol of server share and a symbol of credibility. Direct deletion is disrespectful to the author.

You can choose to modify the information in the package when you use it yourself, orerwrite the implementation of the HTTP protocol yourself, instead of directly letting the original project delete its identity.

--------------------

安全不应该只是做表面的工作，修改 server 标识的返回，无论是迷惑还是去除，存在的的漏洞还是存在的。

server 的标识还有其他用途，也是服务器占有率的象征，和信誉的象征。直接删除是对作者的不尊重。

你可以选择在自己使用时修改包内信息，或者在项目中自己写 HTTP 协议的实现，而不能直接让原项目删除其标识。

**Comment by walkor** [comment]
Adding a configuration for that is not cost-effective, and it is speculated that 90% of people will not set it. Deleting `server` header by passing an empty `server` header appears to be a compromise solution.
```php
$worker->onMessage = function (TcpConnection $connection, Request $request) {
    $response = new Response(200, ['server' => ''], 'body');
    $connection->send($response);
};
```

**Comment by joanhey** [comment]
What they want to hide?
Workerman? or their app code?

**Comment by joanhey** [comment]
How can anybody report a problem to Workerman, without the server header ?

**Comment by joanhey** [comment]
Never a server hide the server header.
Also very problematic apps, everybody know the app?
Example: wordpress, drupal, ...

**Comment by joanhey** [comment]
Any app have a lot of more security problems, than a server!!!
It's good to hide the version. But not the server header, or your app URL.

With a security problem, any good hacker check the vulnerability, not the server or app.
It's irrelevant the server or app, they only check for the security hole.

**Comment by eusonlito** [comment]
@joanhey all internet related servers has an option to hide de server version to avoid direct atacks agains version vectors.

Apache: `ServerSignature Off`
nginx: `server_tokens off;`
PHP: `expose_php = off`
ProFTPd: `ServerIdent off`

And there are a lot of more examples.

**Comment by joanhey** [comment]
@eusonlito yes, the server version.
Try to disable also the server name to Nginx.

**Comment by eusonlito** [comment]
@joanhey yes, I'm commenting about the server details (version).

**Comment by walkor** [comment]
Ok, according to the discussion, keep the server header and remove version information.

**Pull request closed without merging**
