### PR TITLE
Predefined Constants first

### PR DESCRIPTION
**Pull request by farwish**

### CODE REVIEW

**Comment by walkor** [comment]
Sorry, the pull request is refused because there is no difference after merge the pull request.

**Comment by xpader** [comment]
Use Constant is more good performance, why not merge it?
A little performance improvement.
No any bad things.

**Comment by walkor** [comment]
There is no description for the pull request. And I see there is other changes(Merge pull request #1 from walkor/master …) which I not sure if it's ok.

A small performance here is not helpful for the business.
No any bad things but no any good things.

But still thanks to farwish.

**Comment by xpader** [comment]
💀

**Pull request closed without merging**
