### PR TITLE
Update tests version libs to fix warnings and deprecations

### PR DESCRIPTION
**Pull request by joanhey**
v1.6.x work OK with PHP 8.4 (without deprecations)

And add ansi color output to composer in the workflow.

Updated workflow actions.

### CODE REVIEW

**Comment by joanhey** [comment]
Before composer color

image


After
image

**Comment by walkor** [comment]
Thank you very much @joanhey . I'm not sure how much work it will be to add tests for Workerman v4, and since Workerman v5 is about to be released, I don't want the testing for Workerman v4 to take up too much of your time.

**Comment by joanhey** [comment]
Are functional tests that work with any runtime.
Also with the PHP CLI Server (than have more fails than Workerman or Adapterman, I'll create an issue to php-src).
For Workerman v4 are ready.

But you can help to create it for Workerma v5
Only create it changing this to v5
https://github.com/joanhey/TestMan/blob/main/tests/Servers/Workerman4.php

Thank you !!

**Comment by walkor** [comment]
Thank you for your efforts and contributions! I'm glad to see that these feature tests can work in multiple runtime environments. That's great!

**Comment by joanhey** [comment]
@walkor 
Please try to name the RCs correctly, so it'll be easier to test.

> In Composer, RC versions are denoted by a suffix -RC<version> (e.g., 1.1-RC1, 2.0-RC2).

**Comment by joanhey** [comment]
The people are crazy about unit tests, but are only for domain (app) logic.
Any runtime (or server) need to meet the same http rules.

**Comment by joanhey** [comment]
Later we need to run that functional tests with any event loop system.

**Comment by joanhey** [comment]
One question??
```
------------------------------------------------ WORKERMAN -------------------------------------------------
Workerman version:5.0.0-rc.2    PHP version:8.1.30 (Jit off)
------------------------------------------------- WORKERS --------------------------------------------------
```
We can change that for RFC3875 compliance
https://php.watch/versions/8.3/cli-server-server-software-changes
```
------------------------------------------------ WORKERMAN -------------------------------------------------
Workerman/5.0.0-rc.2    PHP/8.1.30 (Jit off)
------------------------------------------------- WORKERS --------------------------------------------------
```

So we have more space to add extra information.

Actually Adapterman use it too.
`Adapterman/0.6.1 (Workerman/4.2.0) OK`

**Comment by walkor** [comment]
#1066 
Done

**Comment by joanhey** [comment]
Added Workerman v4 and v5 to Testman.
Both using the same server file.

But v5 fail in one test (session destroy) and perhaps it's a bug in v5, as both use the same server file.

Workerman/4
https://github.com/joanhey/TestMan/actions/runs/11732788915/job/32685757726

Workerman/5
https://github.com/joanhey/TestMan/actions/runs/11732788887/job/32685757580

Workerman session code in server
https://github.com/joanhey/TestMan/blob/main/tests/Servers/Workerman.php#L185-L231

Pest code for session destroy
https://github.com/joanhey/TestMan/blob/main/tests/Functional/Session/SessionTest.php#L76

@walkor can you check it

Thank you

**Comment by walkor** [comment]
Okay, I will fix it right away.

**Comment by joanhey** [comment]
Working OK !!
Using dev-master
https://github.com/joanhey/TestMan/actions/runs/11746572674

**Comment by joanhey** [comment]
mm still another problem.
It's easy to fix:
image

**Pull request merged**
