### PR TITLE
forced stop master process

### PR DESCRIPTION
**Pull request by malacca**
all worker process maybe has exit, but master process still can not stop, check worker running status and stop master process

### CODE REVIEW

**Comment by walkor** [comment]
Thank you for your pr.
But how can I reproduce this problem?

**Comment by malacca** [comment]
sorry, I still don't know how to reproduce.  
I use workerman on centos7,  test same code many many times, it happened sometimes, not always

maybe worker process stop, but not run this code
https://github.com/walkor/Workerman/blob/master/Worker.php#L1451

so, if only use static::$_pidMap to check worker process status, it will be never stop sucessful
https://github.com/walkor/Workerman/blob/master/Worker.php#L1476

 i add these code,  and test same code,  it work fine everytime.

i think it's system compatibility issues, this is just in case

**Comment by malacca** [comment]
added one new change,  for win version,  may be start file not have .php extension
is_file() verification  is enough

i  have test case,  include first pr, how to give you ?

**Comment by walkor** [comment]
Thanks a lot.

**Pull request merged**
