### PR TITLE
Remome init timezone, display errors and error reporting. Than must be configured by application.

### PR DESCRIPTION
**Pull request by l2ping**
…e configured by application.

### CODE REVIEW

**Comment by linkec** [comment]
I thought this will not fixed, whether you disabled Error reporting, then you are not able to track the crash.

**Comment by l2ping** [comment]
> I thought this will not fixed, whether you disabled Error reporting, then you are not able to track the crash.

It is strange to customize the application settings in the library.

**Comment by linkec** [comment]
this is for debug , you can disable it when you finish your development.
but tbh , these warning/error messages are useful during your program is running.
you can quick track to the error and find out where is wrong.
I strongly suggest do not turn it off.

**Comment by walkor** [comment]
I believe this has been answered, so I'm closing this for now.

**Pull request closed without merging**
