### PR TITLE
connections php doc

### PR DESCRIPTION
**Pull request by ncwsky**

### CODE REVIEW

**Comment by blogdaren** [comment]
> Please, Could you write the phpdoc in Engish.
> Thank You
here it is: 
https://github.com/walkor/workerman-manual/

**Comment by joanhey** [comment]
I don't say the manual, I say the phpdoc.

**Comment by blogdaren** [comment]
well, got it.

> I don't say the manual, I say the phpdoc in the code.

**Comment by joanhey** [comment]
I want to continue collaborating in the project. But it's really difficult to me with the phpdoc en Chinese.
Thank you

**Comment by blogdaren** [comment]
you need to ask walkor for help :) 

then i get puzzled why your IDE show the info in chinese only, what kind of IDE you use?

**Comment by joanhey** [comment]
The IDE show the phpdoc in the code. If the phpdoc is in Chinese, so will show it the IDE.

**Pull request closed without merging**
