### PR TITLE
Temp files processing refactoring

### PR DESCRIPTION
**Pull request by luzrain**
I propose some changes in the way we work with temporary files during the execution of the "status" and "connections" commands.

#### Changes:
 - I have added tho new properties _$processStatusFile_ and _$connectionStatusFile_ instead of _$statusFile_.
 - Moved out initialization process of these properties to the init method.
 - Changed the default paths to the system temp directory.
 - Changed the way files are deleted after command execution. "connection" command didn't delete them at all.
 - Added _formatConnectionStatusData()_ method similar to _formatStatusData()_ but for "connections" command output (it's needed to add the ability to override the way the message is printed).
 - Print "connections" command output using the _safeEcho()_ method.

#### Breaking changes:
 - $_statusFile_ property removed, replaced with _$processStatusFile_ and _$connectionStatusFile_.

#### Breaking changes in protected scope:
May only affect those who have overridden the Workerman class.
 - _formatStatusData()_ method removed, replaced by _formatProcessStatusData()_
 - _$statisticsFile_ property removed

Other changes:
Pid file default path also uses system temp directory by default.
Sleep time during "status" command execution reduced to 0.5sec.

### CODE REVIEW

**Comment by luzrain** [comment]
One more thing I want to discuss. Do we even need the ability to set custom paths for status files since they are stored in the system temp directory by default? Maybe it's worth to removing _$processStatusFile_ and _$connectionStatusFile_ from the public scope at all? What do you think?

**Comment by luzrain** [comment]
I've found the reason why the original temp directories were changed, so it might be better to save temp files in the old place. It's up to you.
https://github.com/walkor/workerman/issues/629
Personally, I think it is a bad idea to save any temp files in the vendor directory.

**Comment by walkor** [comment]
Thank you very much for your PR.
I suggest keeping the statusFile so that old projects can be directly upgraded without making any changes.
The default value of pidFile is `sys_get_temp_dir()`, in Linux systems it is likely to be the `/tmp` directory, and many operating systems regularly clean up the `/tmp` directory, resulting in the loss of pid files.

**Comment by luzrain** [comment]
I returned public $statusFile and changed back default system temp paths 👌

**Pull request merged**
