### PR TITLE
Update Worker.php

### PR DESCRIPTION
**Pull request by don6105**
execute $onMasterStop at command "stop"

### CODE REVIEW

**Comment by don6105** [comment]
$onMasterStop should work in both debug and daemon mode.

**Comment by walkor** [comment]
> $onMasterStop should work in both debug and daemon mode.

onMasterStop workers fine in both debug and daemon mode.
Can you give a simple example to show your problem?

**Comment by don6105** [comment]
`
use Workerman\Worker;
require_once(__DIR__.'/Workerman-master/Autoloader.php');

$worker = new Worker();
$worker->onWorkerStart = function ($task) { echo 'Running'.PHP_EOL; };

Worker::$onMasterStop = function() { echo 'Quit'.PHP_EOL; };  // focus
Worker::runAll();
`

https://imgchr.com/i/wPgJJS


https://imgchr.com/i/wPgUMj

**Comment by don6105** [comment]
```php
<?php

Worker.php:

public static function runAll()
{
       static::checkSapiEnv();
        static::init();
        static::parseCommand();   // command "php start.php stop" exit there
        static::daemonize();
        static::initWorkers();
        static::installSignal();
        static::saveMasterPid();
        static::displayUI();
        static::forkWorkers();
        static::resetStd();
        static::monitorWorkers();   // $onMasterStop be executed there
}
````

**Comment by walkor** [comment]
http://doc.workerman.net/worker/stdout-file.html
All output will redirect to `/dev/null` by default in debug mode. So you can not see any output on screen.

**Comment by don6105** [comment]
OK. I got it. thx.

**Pull request closed without merging**
